Firebase bugfix
- Conclusion:
All these three bug were caused by the migration to the new Swift 5.5 concurrency model and logs generally say “SwiftUI.utils fatal error `SwiftUI/ThreadUtils.swift:114: Fatal error: calling into SwiftUI on a non-main thread is not supported`

So using Task instead of the old bandaid of DispatchQueue.async is being used.  This happens in iOS 17 +

Link:

https://console.firebase.google.com/project/litewallet-beta/crashlytics/app/ios:com.litecoin.loafwallet/issues/7a914e7d2f7be6da1bae099eebe81343?time=last-seven-days&types=crash&sessionEventKey=fb8f22b4239c41468d7f22798c730544_1931864328283447260
Signed-off-by: kcw-grunt <mrkerrywashington@icloud.com>